#!/bin/sh

# Start/stop script to load/unload drivers as per the requirements of assignment 7, part 2

do_load_scull() {
	/sbin/scull_load
}

do_unload_scull() {
	/sbin/scull_unload
}

case "$1" in
	start)
		do_load_scull
		;;
	stop)
		do_unload_scull
		;;
	*)
		echo "Usage: $0 {start|stop}"
esac

exit 0