#!/bin/sh

# Start/stop script to load/unload drivers as per the requirements of assignment 7, part 2

do_load_hello() {
	modprobe hello
}

do_unload_hello() {
	rmmod hello
}

case "$1" in
	start)
		do_load_hello
		;;
	stop)
		do_unload_hello
		;;
	*)
		echo "Usage: $0 {start|stop}"
esac

exit 0